on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Installing dependencies
        run: npm install

      - name: Angular Build
        run: npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: sftp://ssh.jonas-digital.be 
          username: jonas-digital.be
          password: ${{secrets.SERVER_NAME}}
