name: Angular App Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Set up FTP
        uses: wtnb75/ftp-action@v2
        with:
          server: ${{ secrets.FTP_USERNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDir: /path/to/your/website

      - name: Remove existing files on server
        run: |
          curl -Q "DELE /*" ftp://${{ secrets.FTP_USERNAME }} --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}

      - name: Upload files
        run: |
          find ./dist -type f -exec curl -T ftp://${{ secrets.SERVER_NAME }} --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} \;
