name: Build and deploy browser

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.10.0

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --prod

    - name: Set up Android
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Ensure gradlew script is executable
      run: chmod +x ./gradlew

    - name: Build Android APK
      run: |
        ./gradlew assembleDebug
        cp app/build/outputs/apk/debug/app-debug.apk $GITHUB_WORKSPACE/app-debug.apk

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: $GITHUB_WORKSPACE/app-debug.apk

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Installing dependencies
        run: npm install

      - name: Angular Build
        run: npm run build
      
      - name: SFTP mirror
        uses: verbindingsfout/sftp-mirror@v1.6
        with:
          server: ${{ secrets.SERVER_NAME }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local: ./dist/portfolio/browser/
          remote: ./