name: Build and deploy browser

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Installing dependencies
        run: npm install

      - name: Angular Build
        run: npm run build
      
      - name: SFTP mirror
        uses: verbindingsfout/sftp-mirror@v1.6
        with:
          server: ${{ secrets.SERVER_NAME }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local: ./dist/portfolio/browser/
          remote: ./